name: GitBook-Legacy to GitHub Pages
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
env:
  TZ: "Asia/Shanghai"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Install dependency
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y tree calibre xvfb
          npm install gitbook-cli -g
          npm install gitbook-summary -g
          npm install svgexport -g
          gitbook install

      - name: Trigger personal build script
        run: |
          book sm -i node_modules -s '-' -d
          cat HEADER|tee README.md
          echo "\`\`\`" |tee -a README.md
          echo "Notes" |tee -a README.md
          tree --dirsfirst -I '__pycache__|node_modules|*.png|*.gif|_book|*.json|*.jpg'|grep -v '^\.$'|tee -a README.md
          echo "\`\`\`" |tee -a README.md
          if [ ! -d books ];then mkdir books;fi
          gitbook build
          gitbook epub . books/CharlesNotes.epub
          gitbook mobi . books/CharlesNotes.mobi
          cp -r books _book
          rm _book/.gitignore

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: _book
          fqdn: ${{secrets.CUSTOM_DOMAIN}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
